# ----
# Site

title: BV
description: BV API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  market:
    title: Websocket 行情推送
    position_number: 3
  api:
    title: 行情接口
    position_number: 2
  trade:
    title: 账户/交易
    position_number: 1
  capital:
    title: 钱包
    position_number: 4
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "market"
      layout: default
    values:
  -
    scope:
      type: "api"
    values:
      _hide_content: true
  -
    scope:
      type: "trade"
    values:
      _hide_content: true
  -
    scope:
      type: "capital"
    values:
      _hide_content: true
# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
